In [1]:
import sys
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [8]:
a.size

5

In [9]:
a.dtype

dtype('int64')

In [10]:
a[1],a[2]

(2, 3)

In [12]:
a[0:]

array([1, 2, 3, 4, 5])

In [13]:
a[1:3]

array([2, 3])

In [14]:
b = np.array([0, .5, 1, 1.5, 2])

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [17]:
b.dtype

dtype('float64')

In [18]:
d = np.array([{'a': 1}, sys])


In [19]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [21]:
A.ndim

2

In [23]:
A.shape

(2, 3)

In [24]:
A.size

6

In [25]:
a.sum()

15

In [26]:
a.std()

1.4142135623730951

In [28]:
A.sum(axis=0)

array([5, 7, 9])

In [29]:
A.sum(axis=1)

array([ 6, 15])

In [30]:

a >= 2


array([False,  True,  True,  True,  True])

In [31]:
a[a >= 2]


array([2, 3, 4, 5])

In [32]:
a[~(a > a.mean())]


array([1, 2, 3])

In [33]:
a[a>a.mean()]

array([4, 5])

In [35]:
A = np.random.randint(100, size=(3, 3))

In [36]:
A

array([[50, 31, 72],
       [79, 79, 10],
       [18, 98, 63]])

In [37]:
A > 30

array([[ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [38]:
 A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [39]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])


In [40]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [43]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [45]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [46]:
sys.getsizeof(1)

28

In [48]:
np.dtype(int).itemsize

8

In [49]:
sys.getsizeof(1)

28

In [50]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [51]:
np.random.random(size=2)

array([0.89122678, 0.86070392])

In [52]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [53]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [54]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [56]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.zeros((3, 3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
c = np.zeros((3,3),dtype=int).itemsize

In [63]:
c

8

In [64]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
"Hello World"[6]

'W'