In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
a.shape

(3,)

In [9]:
b = np.array([[1.3,2.4],[0.3,4.1]])

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim

2

In [12]:
b.size

4

In [13]:
b.shape

(2, 2)

In [14]:
b.itemsize

8

In [15]:
b.data

In [16]:
e = np.array([(1,2,3),[4,5,6],(7,8,9)])

In [17]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
g = np.array([['a','b'],['c','d']])

In [19]:
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [20]:
g.dtype.name

'str32'

In [21]:
f = np.array([[1,2,3],[4,5,6]],dtype=complex)

In [22]:
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [23]:
f.ndim

2

In [24]:
f.shape

(2, 3)

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [31]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [32]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
np.linspace(0,10,2)

array([ 0., 10.])

In [36]:
np.random.randint(3)

2

In [37]:
np.random.random(3)

array([0.3613699 , 0.87740626, 0.98495356])

In [38]:
np.random.random((3,3))

array([[0.44312841, 0.07969646, 0.26660138],
       [0.51915928, 0.82081551, 0.53722169],
       [0.77633885, 0.77112548, 0.56498848]])

In [39]:
a = np.arange(4)

In [40]:
a

array([0, 1, 2, 3])

In [41]:
a + 4

array([4, 5, 6, 7])

In [42]:
a * 2

array([0, 2, 4, 6])

In [43]:
b = np.arange(4,8)

In [44]:
b

array([4, 5, 6, 7])

In [45]:
a + b

array([ 4,  6,  8, 10])

In [46]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [47]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [49]:
A = np.arange(0,9).reshape(3,3)

In [50]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
B = np.ones((3,3))

In [52]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [54]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [55]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [56]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [57]:
a = np.arange(1,5)

In [58]:
a

array([1, 2, 3, 4])

In [59]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [60]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [61]:
a = np.array([3.3,4.5,1.2,5.7,0.3])

In [62]:
a.sum()

15.0

In [63]:
a.min()

0.3

In [64]:
a.max()

5.7

In [65]:
a.mean()

3.0

In [66]:
a.std()

2.0079840636817816

In [67]:
a[-1]

0.3

In [69]:
a[[1,2,3]]

array([4.5, 1.2, 5.7])

In [70]:
A = np.arange(10,19).reshape((3,3))

In [71]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
a[1:5]

array([4.5, 1.2, 5.7, 0.3])

In [73]:
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [74]:
a[1:5:2]

array([4.5, 5.7])

In [75]:
a[::2]

array([3.3, 1.2, 0.3])

In [76]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [77]:
A[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [78]:
for row in a:
    print(row)

3.3
4.5
1.2
5.7
0.3


In [79]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [80]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [81]:
np.apply_along_axis(np.mean,axis=0,arr=A)

array([13., 14., 15.])

In [82]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [84]:
np.apply_along_axis(np.mean,axis=1,arr=A)

array([11., 14., 17.])

In [85]:
def foo(x):
    return x/2

In [87]:
np.apply_along_axis(foo,axis=1,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [88]:
def add(x):
    return x + 1

In [89]:
np.apply_along_axis(add,axis=1,arr=A)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [90]:
np.apply_along_axis(add,axis=0,arr=A)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [91]:
np.random.random((4,4))

array([[0.67494465, 0.70662803, 0.77206797, 0.36156238],
       [0.1607785 , 0.2304205 , 0.05214785, 0.22870613],
       [0.45098882, 0.39868597, 0.65676394, 0.55387938],
       [0.70322438, 0.89831616, 0.93824132, 0.31579944]])

In [92]:
A[A < 0.5]

array([], dtype=int64)

In [93]:
A < 0.5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [94]:
A[A < 0.5]

array([], dtype=int64)

In [96]:
A < 0.5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [97]:
a = np.random.random(12)

In [98]:
a

array([0.71549115, 0.48962075, 0.6724743 , 0.45687866, 0.60686374,
       0.97407401, 0.06750782, 0.22203426, 0.96867148, 0.91337472,
       0.94468659, 0.24063439])

In [99]:
a.reshape((3,4))

array([[0.71549115, 0.48962075, 0.6724743 , 0.45687866],
       [0.60686374, 0.97407401, 0.06750782, 0.22203426],
       [0.96867148, 0.91337472, 0.94468659, 0.24063439]])

In [100]:
a.ravel()

array([0.71549115, 0.48962075, 0.6724743 , 0.45687866, 0.60686374,
       0.97407401, 0.06750782, 0.22203426, 0.96867148, 0.91337472,
       0.94468659, 0.24063439])

In [101]:
a.shape = (12)

In [102]:
a

array([0.71549115, 0.48962075, 0.6724743 , 0.45687866, 0.60686374,
       0.97407401, 0.06750782, 0.22203426, 0.96867148, 0.91337472,
       0.94468659, 0.24063439])

In [103]:
A.transpose()

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [104]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [105]:
A = np.ones((3,3))

In [106]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
B = np.ones((3,3))

In [108]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.hstack((A,B))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [110]:
c = a.copy()

In [111]:
c

array([0.71549115, 0.48962075, 0.6724743 , 0.45687866, 0.60686374,
       0.97407401, 0.06750782, 0.22203426, 0.96867148, 0.91337472,
       0.94468659, 0.24063439])

In [113]:
structured = np.array([(1,'First',0.5, 1+ 2j),(2,'Second',1.3,2-2j),(3,'Third',0.8,1+3j)],dtype=('i2, a6,f4,c8'))

In [114]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [115]:
structured['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [117]:
data = np.genfromtxt('data.csv',delimiter=',',names=True)

In [118]:
data

array([(1., 123., 1.4, 23.), (2., 110., 0.5, 18.), (3., 164., 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [119]:
data['id']

array([1., 2., 3.])