In [2]:
import numpy as np


In [2]:
p = np.array([48.858598,2.294495])

In [3]:
p

array([48.858598,  2.294495])

In [4]:
p.ndim


1

In [5]:
p.dtype

dtype('float64')

In [6]:
p.shape

(2,)

In [7]:
len(p)

2

In [8]:
p.dtype

dtype('float64')

In [10]:
float_b = p.astype(np.float64)

In [11]:
p.dtype

dtype('float64')

In [12]:
float_b

array([48.858598,  2.294495])

In [13]:
int_p = p.astype(np.int64)

In [14]:
int_p

array([48,  2])

In [15]:
int_p.dtype

dtype('int64')

In [16]:
np.empty([3,2],dtype=np.float64)

array([[1.58642414e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [17]:
np.empty([3,2],dtype=np.int8)

array([[1, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [19]:
a = np.array([[1,2],[4,3]])

In [20]:
a.shape

(2, 2)

In [21]:
a.dtype

dtype('int64')

In [23]:
a.ndim

2

In [24]:
len(a)

2

In [25]:
new_int = a.astype(np.int8)

In [26]:
new_int

array([[1, 2],
       [4, 3]], dtype=int8)

In [27]:
np.empty_like(new_int)

array([[ -67,   55],
       [-122,   53]], dtype=int8)

In [30]:
c = np.array([[0,0],[0,0]])

In [31]:
np.empty_like(c)

array([[32243227,        0],
       [       1,       -1]])

In [33]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [34]:
np.identity(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [37]:
x = np.array([[0,1,2,],[3,4,5]])


In [38]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
np.empty_like(x)

array([[30912698,        0,        0],
       [       0,        0,        0]])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [42]:
np.arange(2,5)

array([2, 3, 4])

In [43]:
np.arange(4,12,5)

array([4, 9])

In [44]:
np.full((2,2),3,dtype=int)

array([[3, 3],
       [3, 3]])

In [45]:
x = np.ones(3)


In [46]:
np.full_like(x,2)

array([2., 2., 2.])

In [47]:
a = [2,3,3,4,5]

In [48]:
np.asarray(a)

array([2, 3, 3, 4, 5])

In [49]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
np.copy(a)

array([2, 3, 3, 4, 5])

In [53]:
a[0]

2

In [54]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
d[0,2]

3

In [56]:
d[0,2] = 10

In [58]:
d.dtype

dtype('int64')

In [59]:
d.shape

(3, 3)

In [60]:
d.ndim

2

In [61]:
d

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [62]:
np.zeros_like(d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
c = d[:2]

In [70]:
q = np.array([3,5,1,10])

In [71]:
b = (q%5 == 0)

In [72]:
b

array([False,  True, False,  True])

In [73]:
c = np.array([[0,1,],[2,3],[4,5],[6,7]])

In [74]:
c[b]

array([[2, 3],
       [6, 7]])

In [75]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [76]:
a[[2,1]]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [77]:
a[[-2,-1]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
a[[2,3],[0,1]]

array([ 9, 14])

In [79]:
a = np.ones(4)

In [80]:
a * 2

array([2., 2., 2., 2.])

In [81]:
a + 3

array([4., 4., 4., 4.])

In [82]:
a = np.array([[0,5,10],[20,25,30]])

In [83]:
a.shape

(2, 3)

In [84]:
a.reshape(3,2)

array([[ 0,  5],
       [10, 20],
       [25, 30]])

In [85]:
np.sort(a)

array([[ 0,  5, 10],
       [20, 25, 30]])

In [3]:
a = np.array([[6,34,1,6],[0,5,2,-1]])

In [4]:
np.sort(a) #sort along the last axis

array([[ 1,  6,  6, 34],
       [-1,  0,  2,  5]])

In [5]:
np.sort(a,axis=0)

array([[ 0,  5,  1, -1],
       [ 6, 34,  2,  6]])

In [6]:
np.argmax(a)

1

In [7]:
a = np.array([[2,4],[3,5]])

In [8]:
np.sum(a,axis=0)

array([5, 9])

In [9]:
np.prod(a,axis=0)

array([ 6, 20])

In [10]:
np.prod(a)


120

In [11]:
np.std(a)

1.118033988749895

In [15]:
a = np.arange(4)

In [16]:
b = np.arange(7)

In [17]:
np.savez('test.npz',arr0=a,arr1=b)

In [18]:
dic = np.load('test.npz')

In [19]:
dic['arr0']

array([0, 1, 2, 3])

In [20]:
x = np.arange(4)


In [22]:
np.savetxt('test3.out',x,delimiter=',')

In [26]:
np.loadtxt('test3.out',delimiter=',')

array([0., 1., 2., 3.])

In [28]:
A = np.array([[1,4,6],[5,2,2],[-1,6,8]])

In [29]:
w,v = np.linalg.eig(A)

In [30]:
w

array([-0.1111635 +1.57564872j, -0.1111635 -1.57564872j,
       11.22232699+0.j        ])

In [31]:
v

array([[-0.09815679+0.27262295j, -0.09815679-0.27262295j,
         0.57642041+0.j        ],
       [ 0.76830893+0.j        ,  0.76830893-0.j        ,
         0.45911115+0.j        ],
       [-0.56562092-0.07626488j, -0.56562092+0.07626488j,
         0.67598555+0.j        ]])

In [32]:
np.random.seed(20)

In [33]:
np.random.rand(5)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959])

In [34]:
np.random.rand(5)

array([0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022])

In [35]:
np.random.seed(20)

In [38]:
np.random.randint(10,20,5)

array([16, 19, 18, 12, 13])

In [39]:
np.random.randint(0,100,99)

array([81, 22, 21, 81, 97, 83, 82, 97,  4,  9, 36, 86,  3, 64, 38, 72, 92,
       82, 34, 73, 44,  2, 80, 69, 86, 38, 91, 72, 49, 10, 72, 51, 59, 65,
       20, 97, 89,  7, 78, 37, 51, 99, 54, 97, 72, 60,  8, 43, 50, 52, 77,
        0, 57, 61, 46, 23, 24, 74, 15, 61, 18, 88, 87, 20, 98, 86, 82,  5,
       30, 85, 95,  0,  4, 50, 87, 45, 90, 47, 12, 38, 48,  7, 61, 91, 90,
       46, 82, 18, 15, 67, 25, 96, 32, 94, 55, 22, 78,  5, 35])

In [40]:
a = np.arange(10)

In [41]:
np.random.shuffle(a)

In [42]:
a


array([2, 3, 7, 8, 0, 5, 9, 4, 1, 6])

In [43]:
b = np.array([[2,3,4,5],[8,9,7,6]])

In [44]:
b

array([[2, 3, 4, 5],
       [8, 9, 7, 6]])

In [49]:
c = b.astype('int8')

In [50]:
c

array([[2, 3, 4, 5],
       [8, 9, 7, 6]], dtype=int8)

In [51]:
b.reshape(4,2)

array([[2, 3],
       [4, 5],
       [8, 9],
       [7, 6]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.savetxt('test1.out',b,delimiter=',')

In [56]:
np.loadtxt('test1.out',delimiter=',')

array([[2., 3., 4., 5.],
       [8., 9., 7., 6.]])

In [57]:
a = np.array([1,2])

In [58]:
b = np.array([3,4])

In [59]:
np.dot(a,b)

11

In [60]:
a * b

array([3, 8])